---
- name: Influx binary exist?
  ansible.builtin.stat:
    path: "/usr/bin/influx"
  register: influxdb_bin

- name: If influxdb exist block
  when: influxdb_bin.stat.exists
  block:
    - name: Fetch the influxd auth list
      no_log: "{{ mylab_nolog | default(true) }}"
      ansible.builtin.command: "/usr/bin/influx auth list --json"
      become: true
      register: cmd_result
      failed_when: cmd_result.rc != 0
      changed_when: false

    - name: Update influxdb configs with operator token
      no_log: "{{ mylab_nolog | default(true) }}"
      when: telgraf2influxdb_configs.localhost.token | default('') | length == 0
      ansible.builtin.set_fact:
        telgraf2influxdb_configs: "{{ telgraf2influxdb_configs |
          combine({ 'localhost': { 'token': (cmd_result.stdout | from_json | selectattr('description', 'eq', 'system-operator') | first).token }},
          recursive=True) }}"
