---
# tasks file for telegraf


- block: 

  - name: Package install
    ansible.builtin.include_tasks:
      file: "{{ ansible_distribution }}-install.yml"

  - name: Configure the plugins
    ansible.builtin.include_tasks:
      file: telegrafd-setup.yml

  # All the secrets are passed in via an evironment file
  - name: copy config to /etc/default/telegraf
    ansible.builtin.copy:
      src: "{{ influx_defaults }}"
      dest: /etc/default/telegraf
      group: telegraf
      mode: 0640
      decrypt: true
      force: true
    register: config_status
    become: true

  - ansible.builtin.debug:
      var: config_status
      verbosity: 1


  # SMELL: Used for an HTTPS influxdb.  This might should be elsewhere.
  - name: copy lets encrypt ca  to  /etc/ssl/certs/
    ansible.builtin.copy:
      src: lets_encrypt_ca.cer 
      dest: /etc/ssl/certs/lets_encrypt_ca.cer
      mode: 0644
    become: true


  - name: systemd reload configs and restart telegraf
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: telegraf
      state: restarted
      enabled: true
    become: true


  when: telegraf_state == 'present'

- block:

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "{{ ansible_distribution }}-rm.yml"

  - name: "Remove the config file"
    ansible.builtin.file:
      path: /etc/telegraf/telegraf.d
      state: absent
    become: true

  - name: "Remove the default file"
    ansible.builtin.file:
      path: /etc/default/telegraf
      state: absent
    become: true

  when: telegraf_state == 'absent'