---

- block:

  #..............................................
  # These are the default inputs....no output!
  #
  - name: clear the telegraf.d configuraiton files
    ansible.builtin.file:
      path: /etc/telegraf/telegraf.d
      state: absent

  - name: copy telegraf.d configuration files
    ansible.builtin.copy:
      src: telegraf.d
      dest: /etc/telegraf/
    notify: 
      - restart telegraf

  #..............................................
  # Specialized inputs
  #
  - name: collect apache stats
    ansible.builtin.copy:
      src: apache.conf
      dest: /etc/telegraf/telegraf.d/apache.conf
    when: influxdb_apache

  - name: collect memcache stats
    ansible.builtin.copy:
      src: memcache.conf
      dest: /etc/telegraf/telegraf.d/memcache.conf
    when: influxdb_memcache

  - name: collect redis stats
    ansible.builtin.copy:
      src: redis.conf
      dest: /etc/telegraf/telegraf.d/redis.conf
    when: influxdb_redis

  - name: collect mariadb stats
    ansible.builtin.copy:
      src: mariadb.conf
      dest: /etc/telegraf/telegraf.d/mariadb.conf
    when: influxdb_mariadb

  - name: collect influxdb stats
    ansible.builtin.copy:
      src: oss-metrics.conf
      dest: /etc/telegraf/telegraf.d/oss-metrics.conf
    when: influxdb_oss_metrics

  become: true

