---
- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_password }}"

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_password }}"

- name: Remove remote root access
  mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_password }}"
  with_items:
    - "%"
    - "::1"
    - "127.0.0.1"
    - "localhost.localdomain"
  when: item != 'localhost'
  