---

# ........................................................................

- name: Create /etc/postfix iff required due to apt issue
  ansible.builtin.file:
    path: /etc/postfix
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Postfix
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: postfix_main.cf.j2, dest: /etc/postfix/main.cf }
    - { src: postfix_master.cf.j2, dest: /etc/postfix/master.cf }
    - { src: postfix_mysql_virtual_domains.cf.j2, dest: /etc/postfix/mysql_virtual_domains.cf }
    - { src: postfix_mysql_virtual_mailboxes.cf.j2, dest: /etc/postfix/mysql_virtual_mailboxes.cf }
    - { src: postfix_mysql_virtual_aliases.cf.j2, dest: /etc/postfix/mysql_virtual_aliases.cf }
  notify: restart postfix
  tags: [postfix_config]

# ........................................................................
- name: Create /etc/dovecot iff required due to apt issue
  ansible.builtin.file:
    path: /etc/dovecot/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Dovecot
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: dovecot.conf.j2, dest: /etc/dovecot/dovecot.conf }
    - { src: dovecot-sql.conf.j2, dest: /etc/dovecot/dovecot-sql.conf.ext }
  notify: restart dovecot
  tags: [dovecot_config]

- name: Add www-data to dovecot group
  user:
    name: www-data
    groups: dovecot
    append: yes
  notify: restart php-fpm
  tags: [dovecot_config]

- name: Configure IMAP monitoring
  template:
    src: dovecot-metrics.conf.j2
    dest: /etc/dovecot/conf.d/90-metrics.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart dovecot
  tags: [dovecot_config]
  

# ..............................................................
- name: Create vmail group
  group:
    name: vmail
    gid: 5000
    system: yes
  tags: [mail_setup]

- name: Create vmail user
  user:
    name: vmail
    uid: 5000
    group: vmail
    home: /var/vmail
    shell: /usr/sbin/nologin
    system: yes
  tags: [mail_setup]

- name: Create vmail directory
  file:
    path: /var/vmail
    state: directory
    owner: vmail
    group: vmail
    mode: '0770'
  tags: [mailconfig]

- name: Ensure vmail user exists
  user:
    name: vmail
    system: yes
    home: /var/vmail
    shell: /usr/sbin/nologin
    uid: 5000  # You might want to adjust this UID
    group: vmail
  tags: [mailconfig]

- name: Ensure vmail group exists
  group:
    name: vmail
    system: yes
    gid: 5000  # You might want to adjust this GID
  tags: [mailconfig]


# ........................................................................
- name: Create /etc/rspamd iff required due to apt issue
  ansible.builtin.file:
    path: /etc/rspamd/local.d
    state: directory
    owner: _rspamd
    group: _rspamd
    mode: '0755'

- name: Configure Rspamd
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: _rspamd
    group: _rspamd
    mode: '0640'
  loop:
    - { src: rspamd_redis.conf.j2, dest: /etc/rspamd/local.d/redis.conf }
    - { src: rspamd_worker.conf.j2, dest: /etc/rspamd/local.d/worker-normal.inc }
  notify: restart rspamd
  tags: [rspamd_config]


