---
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution|lower }}.yml"

- name: Generate random passwords
  when: mailsvc_state == "present"
  block:
    - name: Generate postfixadmin password
      set_fact:
        postfixadmin_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits,punctuation') }}"

    - name: Generate cubemail password
      set_fact:
        cubemail_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits,punctuation') }}"

    - name: Save passwords to remote file
      copy:
        dest: "{{ password_file }}"
        content: |
          PostfixAdmin Password: {{ postfixadmin_password }}
          Cubemail Password: {{ cubemail_password }}
          MySQL Root Password: {{ mysql_password }}
        mode: '0600'

    - name: Fetch password file locally
      fetch:
        src: "{{ password_file }}"
        dest: "{{ local_password_file }}"
        flat: yes

- name: Include OS-specific package tasks
  include_tasks: "packages_{{ ansible_distribution|lower }}.yml"

- name: Include database management tasks
  include_tasks: database.yml

- name: Include configuration tasks
  include_tasks: config.yml

- name: Ensure services are started and enabled
  when: mailsvc_state == "present"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - postfix
    - dovecot
    - "{{ php_service }}"
    - rspamd

- name: Remove configuration directories
  when: 
    - mailsvc_state == "absent"
    - mailsvc_remove_config | bool
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ config_paths }}"

- name: Remove data directories
  when:
    - mailsvc_state == "absent"
    - mailsvc_remove_data | bool
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ data_paths }}"
