---
- name: Manage mail service packages for Debian
  apt:
    name: "{{ mailsvc_packages }}"
    state: "{{ mailsvc_state }}"
    update_cache: yes
    autoremove: "{{ mailsvc_state == 'absent' }}"
    purge: "{{ mailsvc_state == 'absent' }}"
