---
- name: Generate database passwords
  set_fact:
    db_passwords: "{{ db_passwords | default({}) | combine({
      item.key: lookup('password', '/dev/null chars=ascii_letters,digits length=16')
    }) }}"
  loop: "{{ databases | dict2items }}"
  no_log: true

- name: Create databases
  mysql_db:
    name: "{{ item.value.name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_password }}"
  loop: "{{ databases | dict2items }}"

- name: Create database users
  mysql_user:
    name: "{{ item.value.user }}"
    password: "{{ db_passwords[item.key] }}"
    priv: "{{ item.value.name }}.*:ALL"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mysql_password }}"
  loop: "{{ databases | dict2items }}"
  no_log: true

- name: Create local data directory
  file:
    path: "./data"
    state: directory
    mode: '0700'
  delegate_to: localhost

- name: Save credentials locally
  copy:
    content: |
      MySQL Root Password: {{ mysql_password }}
      {% for db_name, password in db_passwords.items() %}
      {{ databases[db_name].user }} Password: {{ password }}
      {% endfor %}
    dest: "{{ mailsvc_local_creds_path }}"
    mode: '0600'
  delegate_to: localhost
  no_log: true

- name: Save credentials on remote
  copy:
    content: |
      MySQL Root Password: {{ mysql_password }}
      {% for db_name, password in db_passwords.items() %}
      {{ databases[db_name].user }} Password: {{ password }}
      {% endfor %}
    dest: "{{ mailsvc_creds_path }}"
    mode: '0600'
  no_log: true
