# Add this task after the nginx.conf template task

# ........................................................................
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/mail.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
  tags: [nginx_config]

- name: Create landing page directory
  file:
    path: /var/www/html/mail
    state: directory
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0755'
  tags: [nginx_config]

- name: Create landing page
  template:
    src: index.html.j2
    dest: /var/www/html/mail/index.html
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0644'
  tags: [nginx_config]

# ........................................................................
- name: Configure PostfixAdmin
  template:
    src: postfixadmin-config.local.php.j2
    dest: "{{ postfixadmin_config_path }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0640'
  notify: restart php-fpm
  tags: [postfixadmin_config]


- name: Create PostfixAdmin setup.php file
  template:
    src: postfixadmin-setup.php.j2
    dest: /usr/share/postfixadmin/templates_c/setup.php
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0640'
  tags: [postfixadmin_setup]

- name: Ensure templates_c directory exists with correct permissions
  file:
    path: /usr/share/postfixadmin/templates_c
    state: directory
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0750'
  tags: [postfixadmin_setup]


- name: Create and set permissions for Ansible temp directory
  file:
    path: /tmp/ansible-tmp
    state: directory
    mode: '1777'  # world-writable with sticky bit
  tags: [postfixadmin_setup]

# Then run the upgrade with better error handling
- name: Run PostfixAdmin upgrade script
  command: php /usr/share/postfixadmin/public/upgrade.php
  args:
    chdir: /usr/share/postfixadmin/public
  become: yes
  become_user: "{{ www_user }}"
  register: upgrade_result
  ignore_errors: yes
  changed_when: false
  tags: [postfixadmin_setup]

- name: Check PostfixAdmin upgrade status
  fail:
    msg: "PostfixAdmin upgrade failed: {{ upgrade_result.stdout | default('Unknown error') }}"
  when: upgrade_result is failed
  tags: [postfixadmin_setup]


- name: Create initial PostfixAdmin admin user
  command: "postfixadmin-cli admin add {{ postfixadmin_admin_email }} --superadmin --password {{ postfixadmin_admin_password }}"
  become: yes
  when: mailsvc_create_admin | default(false)
  tags: [postfixadmin_setup] 

# ........................................................................
- name: Configure Roundcube
  template:
    src: roundcube-config.inc.php.j2
    dest: "{{ roundcube_config_path }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0640'
  notify: restart php-fpm
  tags: [roundcube_config]

