---

# ........................................................................

- name: Enable required Apache modules
  command: "a2enmod {{ item }}"
  with_items:
    - proxy_fcgi
    - setenvif
    - php8.3-fpm
    - headers
    - ssl
  notify: restart apache2
  tags: [apache2_config]

- name: Copy Apache virtual host configuration
  template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/mail.conf
    mode: '0644'
  notify: restart apache2
  tags: [apache2_config]

- name: Enable mail virtual host
  command: a2ensite mail.conf
  tags: [apache2_config]

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  tags: [apache2_config]

- name: Create landing page directory
  file:
    path: /var/www/html/mail
    state: directory
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0755'
  tags: [apache2_config]

- name: Create landing page
  template:
    src: index.html.j2
    dest: /var/www/html/mail/index.html
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0644'
  tags: [apache2_config]

# ........................................................................
- name: Create /etc/postfixadmin iff required due to apt issue
  ansible.builtin.file:
    path: /etc/postfixadmin
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [postfixadmin_config]

- name: Configure PostfixAdmin
  template:
    src: postfixadmin-config.local.php.j2
    dest: "{{ postfixadmin_config_path }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0640'
  notify: restart php-fpm
  tags: [postfixadmin_config]


- name: Create PostfixAdmin setup.php file
  template:
    src: postfixadmin-setup.php.j2
    dest: /usr/share/postfixadmin/templates_c/setup.php
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0640'
  tags: [postfixadmin_setup]

- name: Ensure templates_c directory exists with correct permissions
  file:
    path: /usr/share/postfixadmin/templates_c
    state: directory
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0750'
  tags: [postfixadmin_setup]


- name: Create and set permissions for Ansible temp directory
  file:
    path: /tmp/ansible-tmp
    state: directory
    mode: '1777'  # world-writable with sticky bit
  tags: [postfixadmin_setup]

# Then run the upgrade with better error handling
- name: Run PostfixAdmin upgrade script
  command: php /usr/share/postfixadmin/public/upgrade.php
  args:
    chdir: /usr/share/postfixadmin/public
  become: yes
  become_user: "{{ www_user }}"
  register: upgrade_result
  ignore_errors: yes
  changed_when: false
  tags: [postfixadmin_setup]

- name: Check PostfixAdmin upgrade status
  fail:
    msg: "PostfixAdmin upgrade failed: {{ upgrade_result.stdout | default('Unknown error') }}"
  when: upgrade_result is failed
  tags: [postfixadmin_setup]


- name: Create initial PostfixAdmin admin user
  command: "postfixadmin-cli admin add {{ postfixadmin_admin_email }} --superadmin --password {{ postfixadmin_admin_password }}"
  become: yes
  when: mailsvc_create_admin | default(false)
  tags: [postfixadmin_setup] 

# ........................................................................
- name: Create /etc/roundcube iff required due to apt issue
  ansible.builtin.file:
    path: /etc/roundcube
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [roundcube_config]

- name: Create /var/lib/roundcube iff required due to apt issue
  ansible.builtin.file:
    path: /var/lib/roundcube
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [roundcube_config]

- name: Configure Roundcube
  template:
    src: roundcube-config.inc.php.j2
    dest: "{{ roundcube_config_path }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: '0640'
  notify: restart php-fpm
  tags: [roundcube_config]

