---
# tasks file for grafana

  #.......................................  
- block:

  - name: Package install
    ansible.builtin.include_tasks:
      file: "../../shared/grafana/tasks/{{ ansible_distribution }}-install.yml"
    vars:
      package: grafana

  ##################
  # Configure

  - name: copy config to /etc/default/grafana-server
    ansible.builtin.template:
      src: etc-default-grafana-server.j2
      dest: /etc/default/grafana-server
      mode: 0640
    register: config_status
    become: true

  - ansible.builtin.debug:
      var: config_status
      verbosity: 1

  - name: Template config to /etc/grafana/config.yml
    ansible.builtin.template:
      src: client_config.ini.j2
      dest: /etc/grafana/grafana.ini
    become: true

  - name: systemd reload configs and restart Grafana
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: grafana-server
      state: restarted
      enabled: true
    become: true

  # - name: make the dashboards directory
  #   ansible.builtin.file:
  #     path: "{{ grafana__data_dir }}/dashboards"
  #     state: directory
  #   become: true

  - name: copy in dashboards
    ansible.builtin.copy:
      src: provisioning
      dest: "/etc/grafana"
    become: true


  when: grafana_state == 'present'


  #.......................................  
- block:

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "../../shared/any/tasks/{{ ansible_distribution }}-rm.yml"
    vars:
      package: grafana
      service_name: grafana-server.service
  
  - name: "Remove the config files"
    ansible.builtin.file:
      path: /etc/grafana
      state: absent
    become: true

  - name: "Remove the defaults file"
    ansible.builtin.file:
      path: /etc/default/grafana-server
      state: absent
    become: true

  when: grafana_state == 'absent'