---
# tasks file for grafana

  #.......................................  
- name: Install Grafana-Server
  when: grafana_state == 'present'
  block:

  - name: Package install
    ansible.builtin.include_tasks:
      file: "../../shared/grafana/tasks/{{ ansible_os_family }}-install.yml"
    vars:
      package: grafana

  ##################
  # Configure

  - name: copy config to /etc/default/grafana-server
    ansible.builtin.template:
      src: etc-default-grafana-server.j2
      dest: /etc/default/grafana-server
      mode: 0640
    register: config_status
    become: true
    notify:
      - restart grafana

  - ansible.builtin.debug:
      var: config_status
      verbosity: 1

  - name: Template config to /etc/grafana/config.yml
    ansible.builtin.template:
      src: client_config.ini.j2
      dest: /etc/grafana/grafana.ini
    become: true
    notify:
      - restart grafana


  # - name: make the dashboards directory
  #   ansible.builtin.file:
  #     path: "{{ grafana__data_dir }}/dashboards"
  #     state: directory
  #   become: true

  # - name: copy in dashboards
  #   ansible.builtin.copy:
  #     src: provisioning
  #     dest: "/etc/grafana"
  #   become: true


  #.......................................  
- name: Remove Grafana-Server and configuration files.
  block:
  when: grafana_state == 'absent'

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "../../shared/any/tasks/{{ ansible_os_family }}-rm.yml"
    vars:
      package: grafana
      service_name: grafana-server.service
  
  - name: "Remove the config files"
    ansible.builtin.file:
      path: /etc/grafana
      state: absent
    become: true

  - name: "Remove the defaults file"
    ansible.builtin.file:
      path: /etc/default/grafana-server
      state: absent
    become: true
