---
# tasks file for grafana

  #.......................................  
- block:

  - name: Package install
    ansible.builtin.include_tasks:
      file: "{{ ansible_distribution }}-install.yml"

  ##################
  # Configure

  - name: Template config to  /etc/Grafana/config.yml
    ansible.builtin.template:
      src: client_config.yml.j2
      dest: /etc/grafana/config.yml
    become: true

  - name: systemd reload configs and restart Grafana
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: grafana-server
      state: restarted
      enabled: true
    become: true

  when: grafana_state == 'present'


  #.......................................  
- block:

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "../../shared/any/tasks/{{ ansible_distribution }}-rm.yml"
    vars:
      package: grafana
      service_name: grafana.service
  
  - name: "Remove the config file"
    ansible.builtin.file:
      path: /etc/grafana/config.yml
      state: absent
    become: true

  when: grafana_state == 'absent'