---
# tasks file for nfs-client

- block:


  - name: Install NFS client packages
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - nfs-common
    become: true
    when: ansible_facts['os_family'] == "Debian"

  - name: Install the latest version of NFS clients
    ansible.builtin.dnf:
      name: nfs-utils
      state: latest
    become: true
    when: ansible_facts['os_family'] == "RedHat"

  - name: Mount an NFS volume
    ansible.posix.mount:
      src: "{{ item.value.src }}"
      path: "{{ item.value.path }}"
      opts: "{{ item.value.opts }}"
      state: "{{ item.value.state }}"
      fstype: "{{ item.value.fstype }}"
    #loop: "{{ lookup('dict', cluster_nfs_mounts) }}"
    loop: "{{ cluster_nfs_mounts | dict2items }}"
    become: true

  when:  mount_nfs_share
