---
- name: Destroy VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove Proxmox VM
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        node: "{{ lookup('env', 'PROXMOX_NODE') }}"
        name: "clone-test"
        vmid: "9100"
        state: absent
        force: yes
      ignore_errors: yes
