---

# Initialize a new influxdb instance

- name: "create initial Influxdb user"
  ansible.builtin.shell:
    cmd: "/usr/bin/influx setup --org {{ influxdb_org }} --bucket {{ influxdb_bucket }} --username {{ influxdb_username }} --password {{ influxdb_password }} --force"
  register: cmd_result
  failed_when: cmd_result.rc != 0
  become: true

- ansible.builtin.debug:
    var: cmd_result.stdout


#................................................................................
- name: "create initial admin token"
  ansible.builtin.shell:
    cmd: influx auth create --org lavnet --all-access --description admin --json
  register: cmd_result
  failed_when: cmd_result.rc != 0
  become: true
- ansible.builtin.debug:
    var: cmd_result.stdout
    verbosity: 1
- set_fact:
    influx_admin: "{{ cmd_result.stdout| from_json }}"

# - debug:
#     var: influx_admin.id
# - debug:
#     var: influx_admin.token
# - debug:
#     var: influx_admin.description

- name: add  influx_admin to influx_auth_list
  set_fact:
    influx_auth_list: "{{ influx_auth_list | default([]) + [{
        'id': influx_admin.id,
        'token': influx_admin.token,
        'description': influx_admin.description
      }] }}"

- debug:
    var: influx_auth_list




#................................................................................
- name: "create initial operator token"
  ansible.builtin.shell:
    cmd: influx auth create --org lavnet --operator --description operator --json
  register: cmd_result
  failed_when: cmd_result.rc != 0
  become: true
- ansible.builtin.debug:
    var: cmd_result.stdout
    verbosity: 1
- set_fact:
    influx_operator: "{{ cmd_result.stdout| from_json }}"

# - debug:
#     var: influx_operator.id
# - debug:
#     var: influx_operator.token
# - debug:
#     var: influx_operator.description

- name: add  influx_operator to influx_auth_list
  set_fact:
    influx_auth_list: "{{ influx_auth_list | default([]) + [{
        'id': influx_operator.id, 
        'token': influx_operator.token,
        'description': influx_operator.description
      }] }}"

- name: Create auth file for this host
  local_action: 
      module: ansible.builtin.copy
      content: "{{ influx_auth_list  | to_nice_yaml  }}"
      dest: "{{ lookup('env', 'PWD') }}/influx-auth-{{ ansible_hostname }}.yml"
      owner: "{{ lookup('env', 'USER') }}"
      mode: 0640
        
- debug:
    var: influx_auth_list

#................................................................................
#................................................................................
#................................................................................
