---
# tasks file for influxdb

#=============================================================================================================
- block:

  - name: Package install
    ansible.builtin.include_tasks:
      file: "../../shared/influxdb/tasks/{{ ansible_distribution }}-install.yml"
    vars:
      package: influxdb2


  ##################
  # Configure

  - name: "Prepare /etc/influxd"
    ansible.builtin.file:
      path: /etc/influxdb
      state: directory
    become: true

  - name: "Template config for storage in /etc/influxd"
    ansible.builtin.template:
      src: config.toml.j2
      dest: /etc/influxdb/config.toml
    become: true

  - name: Restart service influxd, if running
    ansible.builtin.systemd_service:
      name: influxd
      state: restarted
    become: true

  #.........................
  - name: Initialize a new influxdb instance
    block:

    - include_tasks: initializedb.yml
    #   vars:
    #     influx_auth_dict: []

    # - debug:
    #     var: influx_auth_dict

    rescue:
      - name: Print when errors
        ansible.builtin.debug:
          msg: "Cannot be setup via ansible.\n The script cannot access SSL and/or it was already setup once!!!"
   
  when: influxdb_state == 'present'


#=============================================================================================================
- block:

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "../../shared/influxdb/tasks/{{ ansible_distribution }}-rm.yml"
    vars:
      package: influxdb2

  #.........................
  - block:

    - name: "Remove the default file"
      ansible.builtin.file:
        path: /etc/default/influxdb2
        state: absent
      become: true

    - name: "Remove the config files"
      ansible.builtin.file:
        path: /etc/influxdb
        state: absent
      become: true

    - name: "Remove the root config files"
      ansible.builtin.file:
        path: /root/.influxdbv2
        state: absent
      become: true

    when: influxdb_delete_config

  #.........................
  - name: "Remove the data files in {{ influxdb_data_path }}"
    ansible.builtin.file:
      path: "{{ influxdb_data_path }}"
      state: absent
    become: true
    when: influxdb_delete_data
    

  when: influxdb_state == 'absent'