---
#.....................................................................................

- name: Populate service facts
  ansible.builtin.service_facts:

- set_fact:
    service_running:  false

- set_fact:
    service_running:  true
  when: service_name is in ansible_facts.services.keys()

# - set_fact:
#     service_running:  "'aparmor.service' in ansible_facts.services.keys()'

- name : "Is the service: {{ package }} running?"
  debug:
    var: service_running
    verbosity: 0

- name: "Systemd stop {{ package }}"
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: stopped
  register: cmd_results
  when:  service_running
  become: true

- name : " {{ package }} stopped results"
  debug:
    var: cmd_results
    verbosity: 1

#................................................................
- name: "Remove {{ package }} Package"
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - "{{ package }}"
    autoremove: true
    autoclean: true
    state: absent
  become: true
