---
# tasks file for loki
#

  #.......................................  
- block:

  - name: Is loki running?
    ansible.builtin.include_tasks:
      file: "../../shared/any/tasks/is-service-running.yml"
    vars:
      service_name: loki.service

  #......................................................................................
  # only install it not running or loki_force_reload
  - name: Loki package install
    ansible.builtin.include_tasks:
      file: "../../shared/grafana/tasks/{{ ansible_distribution }}-install.yml"
    vars:
      package: loki
    when: service_running is false or loki_force_reload

  ##################
  # Configure

  - name: Template config to  /etc/loki/config.yml
    ansible.builtin.template:
      src: config.yml.j2
      dest: /etc/loki/config.yml
    become: true
    notify:
      - restart loki
  
  when: loki_state == 'present'

  #....................................................................  
- block:

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "../../shared/any/tasks/{{ ansible_distribution }}-rm.yml"
    vars:
      package: loki
      service_name: loki.service


  - name: "Remove the config files /etc/loki"
    ansible.builtin.file:
      path: /etc/loki
      state: absent
    become: true
    when: loki_delete_config


  - name: "Remove the date files /var/lib/loki/"
    ansible.builtin.file:
      path: "/var/lib/loki/*"
      state: absent
    become: true
    when: loki_delete_data


  when: loki_state == 'absent'
