---
# tasks file for loki
#

  #.......................................  
- block:

  - name: Package install
    ansible.builtin.include_tasks:
      file: "{{ ansible_distribution }}-install.yml"

  ##################
  # Configure

  - name: Template config to  /etc/loki/config.yml
    ansible.builtin.template:
      src: config.yml.j2
      dest: /etc/loki/config.yml
    become: true

  - name: systemd reload configs and restart Loki
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: loki
      state: restarted
      enabled: true
    become: true

  when: loki_state == 'present'

  #.......................................  
- block:

  - name: systemd reload configs and restart Loki
    ansible.builtin.systemd_service:
      name: loki
      state: stop
    become: true

  - name: Package remove
    ansible.builtin.include_tasks:
      file: "{{ ansible_distribution }}-rm.yml"

  - name: "Remove the config file"
    ansible.builtin.file:
      path: /etc/loki/config.yml
      state: absent
    become: true

  when: loki_state == 'absent'
